AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/migrate/*.rb'
    - 'passwordless.gemspec'
    - 'test/dummy/db/schema.rb'
    - 'test/dummy/bin/*'

Layout/AlignHash:
  Exclude:
    - 'Gemfile'

Style/IfUnlessModifier:
  Enabled: false

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Exclude:
    - 'test/dummy/config/routes.rb'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*_test.rb'

Metrics/LineLength:
  Exclude:
    - 'test/dummy/**/*'
